version: 2.1

# Define the jobs  we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          name: build-holochain
          command: | 
            CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown
            dna-util -c testlab.dna.workdir/
      - run:
          name: test-holochain
          working_directory: ~/tests
          command: |
            NODE_ENV=development npm install
            npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-and-test
