[package]
name = "zometwo"
version = "0.0.1"
authors = [ "hcij" ]
edition = "2018"

[lib]
name = "zometwo"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
derive_more = "0"
serde = "1"

hdk3 = {git = "https://github.com/holochain/holochain", rev = "65f768c", package = "hdk3"}