[package]
name = "zomeone"
version = "0.0.1"
authors = [ "hcij" ]
edition = "2018"

[lib]
name = "zomeone"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "=1.0.104"
hdk3 = {path = "../../../holochain/crates/hdk"}
derive_more = "0.99.9"