name: CI
on:
  push:
    branches:
      - main
      - actions-testing
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:

    - name: checkout the code
      uses: actions/checkout@v2

      
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: install bats
      run: npm install -g bats
      
    - name: check version
      run: bats -v